[2025-10-25T14:26:17.171+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-25T14:26:17.221+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dataco_supply_chain_pipeline.dbt_run_core manual__2025-10-25T14:25:10.149871+00:00 [queued]>
[2025-10-25T14:26:17.233+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dataco_supply_chain_pipeline.dbt_run_core manual__2025-10-25T14:25:10.149871+00:00 [queued]>
[2025-10-25T14:26:17.235+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-25T14:26:17.255+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run_core> on 2025-10-25 14:25:10.149871+00:00
[2025-10-25T14:26:17.275+0000] {standard_task_runner.py:64} INFO - Started process 2696 to run task
[2025-10-25T14:26:17.278+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dataco_supply_chain_pipeline', 'dbt_run_core', 'manual__2025-10-25T14:25:10.149871+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/DataCo_pipeline_DAG.py', '--cfg-path', '/tmp/tmpywwenv2x']
[2025-10-25T14:26:17.282+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask dbt_run_core
[2025-10-25T14:26:17.357+0000] {task_command.py:426} INFO - Running <TaskInstance: dataco_supply_chain_pipeline.dbt_run_core manual__2025-10-25T14:25:10.149871+00:00 [running]> on host 2f7836fe1173
[2025-10-25T14:26:17.479+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='bi@example.com' AIRFLOW_CTX_DAG_OWNER='DE-team' AIRFLOW_CTX_DAG_ID='dataco_supply_chain_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_core' AIRFLOW_CTX_EXECUTION_DATE='2025-10-25T14:25:10.149871+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-25T14:25:10.149871+00:00'
[2025-10-25T14:26:17.483+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-25T14:26:17.500+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-25T14:26:17.503+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /usr/app/supply_chain_core && dbt run --select core']
[2025-10-25T14:26:17.517+0000] {subprocess.py:86} INFO - Output:
[2025-10-25T14:26:23.450+0000] {subprocess.py:93} INFO - [0m14:26:23  Running with dbt=1.9.1
[2025-10-25T14:26:24.004+0000] {subprocess.py:93} INFO - [0m14:26:24  Registered adapter: postgres=1.9.1
[2025-10-25T14:26:27.131+0000] {subprocess.py:93} INFO - [0m14:26:27  Found 10 models, 35 data tests, 1 source, 550 macros
[2025-10-25T14:26:27.139+0000] {subprocess.py:93} INFO - [0m14:26:27
[2025-10-25T14:26:27.142+0000] {subprocess.py:93} INFO - [0m14:26:27  Concurrency: 1 threads (target='dev')
[2025-10-25T14:26:27.145+0000] {subprocess.py:93} INFO - [0m14:26:27
[2025-10-25T14:26:27.438+0000] {subprocess.py:93} INFO - [0m14:26:27  1 of 10 START sql table model core_core.categories ............................. [RUN]
[2025-10-25T14:26:29.029+0000] {subprocess.py:93} INFO - [0m14:26:29  1 of 10 OK created sql table model core_core.categories ........................ [[32mSELECT 51[0m in 1.58s]
[2025-10-25T14:26:29.039+0000] {subprocess.py:93} INFO - [0m14:26:29  2 of 10 START sql table model core_core.customers .............................. [RUN]
[2025-10-25T14:26:29.532+0000] {subprocess.py:93} INFO - [0m14:26:29  2 of 10 OK created sql table model core_core.customers ......................... [[32mSELECT 20652[0m in 0.48s]
[2025-10-25T14:26:29.541+0000] {subprocess.py:93} INFO - [0m14:26:29  3 of 10 START sql table model core_core.delivery_status ........................ [RUN]
[2025-10-25T14:26:29.768+0000] {subprocess.py:93} INFO - [0m14:26:29  3 of 10 OK created sql table model core_core.delivery_status ................... [[32mSELECT 4[0m in 0.22s]
[2025-10-25T14:26:29.778+0000] {subprocess.py:93} INFO - [0m14:26:29  4 of 10 START sql table model core_core.departments ............................ [RUN]
[2025-10-25T14:26:29.984+0000] {subprocess.py:93} INFO - [0m14:26:29  4 of 10 OK created sql table model core_core.departments ....................... [[32mSELECT 11[0m in 0.20s]
[2025-10-25T14:26:29.994+0000] {subprocess.py:93} INFO - [0m14:26:29  5 of 10 START sql table model core_core.location ............................... [RUN]
[2025-10-25T14:26:30.738+0000] {subprocess.py:93} INFO - [0m14:26:30  5 of 10 OK created sql table model core_core.location .......................... [[32mSELECT 64990[0m in 0.73s]
[2025-10-25T14:26:30.748+0000] {subprocess.py:93} INFO - [0m14:26:30  6 of 10 START sql table model core_core.order_items ............................ [RUN]
[2025-10-25T14:26:31.382+0000] {subprocess.py:93} INFO - [0m14:26:31  6 of 10 OK created sql table model core_core.order_items ....................... [[32mSELECT 180519[0m in 0.63s]
[2025-10-25T14:26:31.392+0000] {subprocess.py:93} INFO - [0m14:26:31  7 of 10 START sql table model core_core.products ............................... [RUN]
[2025-10-25T14:26:31.632+0000] {subprocess.py:93} INFO - [0m14:26:31  7 of 10 OK created sql table model core_core.products .......................... [[32mSELECT 118[0m in 0.23s]
[2025-10-25T14:26:31.641+0000] {subprocess.py:93} INFO - [0m14:26:31  8 of 10 START sql table model core_core.shipping_mode .......................... [RUN]
[2025-10-25T14:26:31.851+0000] {subprocess.py:93} INFO - [0m14:26:31  8 of 10 OK created sql table model core_core.shipping_mode ..................... [[32mSELECT 4[0m in 0.20s]
[2025-10-25T14:26:31.861+0000] {subprocess.py:93} INFO - [0m14:26:31  9 of 10 START sql table model core_core.orders ................................. [RUN]
[2025-10-25T14:26:31.965+0000] {subprocess.py:93} INFO - [0m14:26:31  9 of 10 ERROR creating sql table model core_core.orders ........................ [[31mERROR[0m in 0.10s]
[2025-10-25T14:26:31.974+0000] {subprocess.py:93} INFO - [0m14:26:31  10 of 10 START sql table model core_core.shipping .............................. [RUN]
[2025-10-25T14:26:32.073+0000] {subprocess.py:93} INFO - [0m14:26:32  10 of 10 ERROR creating sql table model core_core.shipping ..................... [[31mERROR[0m in 0.09s]
[2025-10-25T14:26:32.122+0000] {subprocess.py:93} INFO - [0m14:26:32
[2025-10-25T14:26:32.125+0000] {subprocess.py:93} INFO - [0m14:26:32  Finished running 10 table models in 0 hours 0 minutes and 4.97 seconds (4.97s).
[2025-10-25T14:26:32.250+0000] {subprocess.py:93} INFO - [0m14:26:32
[2025-10-25T14:26:32.253+0000] {subprocess.py:93} INFO - [0m14:26:32  [31mCompleted with 2 errors, 0 partial successes, and 0 warnings:[0m
[2025-10-25T14:26:32.256+0000] {subprocess.py:93} INFO - [0m14:26:32
[2025-10-25T14:26:32.258+0000] {subprocess.py:93} INFO - [0m14:26:32    Database Error in model orders (models/core/orders.sql)
[2025-10-25T14:26:32.259+0000] {subprocess.py:93} INFO -   syntax error at or near ""Order Status""
[2025-10-25T14:26:32.260+0000] {subprocess.py:93} INFO -   LINE 23:         "Order Status" as order_status,
[2025-10-25T14:26:32.261+0000] {subprocess.py:93} INFO -                    ^
[2025-10-25T14:26:32.262+0000] {subprocess.py:93} INFO -   compiled code at target/run/supply_chain_core/models/core/orders.sql
[2025-10-25T14:26:32.263+0000] {subprocess.py:93} INFO - [0m14:26:32
[2025-10-25T14:26:32.264+0000] {subprocess.py:93} INFO - [0m14:26:32    Database Error in model shipping (models/core/shipping.sql)
[2025-10-25T14:26:32.265+0000] {subprocess.py:93} INFO -   syntax error at or near ""Days for shipment (scheduled)""
[2025-10-25T14:26:32.266+0000] {subprocess.py:93} INFO -   LINE 23:         "Days for shipment (scheduled)" as days_for_shipment...
[2025-10-25T14:26:32.267+0000] {subprocess.py:93} INFO -                    ^
[2025-10-25T14:26:32.268+0000] {subprocess.py:93} INFO -   compiled code at target/run/supply_chain_core/models/core/shipping.sql
[2025-10-25T14:26:32.268+0000] {subprocess.py:93} INFO - [0m14:26:32
[2025-10-25T14:26:32.269+0000] {subprocess.py:93} INFO - [0m14:26:32  Done. PASS=8 WARN=0 ERROR=2 SKIP=0 TOTAL=10
[2025-10-25T14:26:34.785+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-25T14:26:34.786+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-25T14:26:34.803+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-25T14:26:34.808+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dataco_supply_chain_pipeline, task_id=dbt_run_core, run_id=manual__2025-10-25T14:25:10.149871+00:00, execution_date=20251025T142510, start_date=20251025T142617, end_date=20251025T142634
[2025-10-25T14:26:34.836+0000] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.10/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-10-25T14:26:34.837+0000] {email.py:271} INFO - Email alerting: attempt 1
[2025-10-25T14:26:38.757+0000] {email.py:282} INFO - Sent an alert email to ['bi@example.com']
[2025-10-25T14:26:40.184+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task dbt_run_core (Bash command failed. The command returned a non-zero exit code 1.; 2696)
[2025-10-25T14:26:40.213+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-25T14:26:40.249+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-25T14:26:40.256+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
