[2025-10-25T12:10:48.156+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-25T12:10:48.237+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dataco_supply_chain_pipeline.dbt_run_core manual__2025-10-25T12:09:49.010461+00:00 [queued]>
[2025-10-25T12:10:48.256+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dataco_supply_chain_pipeline.dbt_run_core manual__2025-10-25T12:09:49.010461+00:00 [queued]>
[2025-10-25T12:10:48.258+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-25T12:10:48.288+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run_core> on 2025-10-25 12:09:49.010461+00:00
[2025-10-25T12:10:48.306+0000] {standard_task_runner.py:64} INFO - Started process 2352 to run task
[2025-10-25T12:10:48.311+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dataco_supply_chain_pipeline', 'dbt_run_core', 'manual__2025-10-25T12:09:49.010461+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/DataCo_pipeline_DAG.py', '--cfg-path', '/tmp/tmpnpmh25s0']
[2025-10-25T12:10:48.314+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask dbt_run_core
[2025-10-25T12:10:48.422+0000] {task_command.py:426} INFO - Running <TaskInstance: dataco_supply_chain_pipeline.dbt_run_core manual__2025-10-25T12:09:49.010461+00:00 [running]> on host 2f7836fe1173
[2025-10-25T12:10:48.576+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='bi@example.com' AIRFLOW_CTX_DAG_OWNER='DE-team' AIRFLOW_CTX_DAG_ID='dataco_supply_chain_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_core' AIRFLOW_CTX_EXECUTION_DATE='2025-10-25T12:09:49.010461+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-25T12:09:49.010461+00:00'
[2025-10-25T12:10:48.578+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-25T12:10:48.593+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-25T12:10:48.595+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /usr/app/supply_chain_core && dbt run --select core']
[2025-10-25T12:10:48.611+0000] {subprocess.py:86} INFO - Output:
[2025-10-25T12:10:54.266+0000] {subprocess.py:93} INFO - [0m12:10:54  Running with dbt=1.9.1
[2025-10-25T12:10:54.863+0000] {subprocess.py:93} INFO - [0m12:10:54  Registered adapter: postgres=1.9.1
[2025-10-25T12:10:58.881+0000] {subprocess.py:93} INFO - [0m12:10:58  Found 10 models, 35 data tests, 1 source, 550 macros
[2025-10-25T12:10:58.890+0000] {subprocess.py:93} INFO - [0m12:10:58
[2025-10-25T12:10:58.892+0000] {subprocess.py:93} INFO - [0m12:10:58  Concurrency: 1 threads (target='dev')
[2025-10-25T12:10:58.895+0000] {subprocess.py:93} INFO - [0m12:10:58
[2025-10-25T12:10:59.221+0000] {subprocess.py:93} INFO - [0m12:10:59  1 of 10 START sql table model core_core.categories ............................. [RUN]
[2025-10-25T12:11:01.237+0000] {subprocess.py:93} INFO - [0m12:11:01  1 of 10 OK created sql table model core_core.categories ........................ [[32mSELECT 51[0m in 2.00s]
[2025-10-25T12:11:01.253+0000] {subprocess.py:93} INFO - [0m12:11:01  2 of 10 START sql table model core_core.customers .............................. [RUN]
[2025-10-25T12:11:01.796+0000] {subprocess.py:93} INFO - [0m12:11:01  2 of 10 OK created sql table model core_core.customers ......................... [[32mSELECT 20652[0m in 0.54s]
[2025-10-25T12:11:01.804+0000] {subprocess.py:93} INFO - [0m12:11:01  3 of 10 START sql table model core_core.delivery_status ........................ [RUN]
[2025-10-25T12:11:02.037+0000] {subprocess.py:93} INFO - [0m12:11:02  3 of 10 OK created sql table model core_core.delivery_status ................... [[32mSELECT 4[0m in 0.23s]
[2025-10-25T12:11:02.047+0000] {subprocess.py:93} INFO - [0m12:11:02  4 of 10 START sql table model core_core.departments ............................ [RUN]
[2025-10-25T12:11:02.290+0000] {subprocess.py:93} INFO - [0m12:11:02  4 of 10 OK created sql table model core_core.departments ....................... [[32mSELECT 11[0m in 0.23s]
[2025-10-25T12:11:02.302+0000] {subprocess.py:93} INFO - [0m12:11:02  5 of 10 START sql table model core_core.location ............................... [RUN]
[2025-10-25T12:11:03.173+0000] {subprocess.py:93} INFO - [0m12:11:03  5 of 10 OK created sql table model core_core.location .......................... [[32mSELECT 64990[0m in 0.86s]
[2025-10-25T12:11:03.182+0000] {subprocess.py:93} INFO - [0m12:11:03  6 of 10 START sql table model core_core.order_items ............................ [RUN]
[2025-10-25T12:11:03.794+0000] {subprocess.py:93} INFO - [0m12:11:03  6 of 10 OK created sql table model core_core.order_items ....................... [[32mSELECT 180519[0m in 0.61s]
[2025-10-25T12:11:03.803+0000] {subprocess.py:93} INFO - [0m12:11:03  7 of 10 START sql table model core_core.products ............................... [RUN]
[2025-10-25T12:11:04.075+0000] {subprocess.py:93} INFO - [0m12:11:04  7 of 10 OK created sql table model core_core.products .......................... [[32mSELECT 118[0m in 0.26s]
[2025-10-25T12:11:04.088+0000] {subprocess.py:93} INFO - [0m12:11:04  8 of 10 START sql table model core_core.shipping_mode .......................... [RUN]
[2025-10-25T12:11:04.344+0000] {subprocess.py:93} INFO - [0m12:11:04  8 of 10 OK created sql table model core_core.shipping_mode ..................... [[32mSELECT 4[0m in 0.25s]
[2025-10-25T12:11:04.352+0000] {subprocess.py:93} INFO - [0m12:11:04  9 of 10 START sql table model core_core.orders ................................. [RUN]
[2025-10-25T12:11:04.449+0000] {subprocess.py:93} INFO - [0m12:11:04  9 of 10 ERROR creating sql table model core_core.orders ........................ [[31mERROR[0m in 0.09s]
[2025-10-25T12:11:04.458+0000] {subprocess.py:93} INFO - [0m12:11:04  10 of 10 START sql table model core_core.shipping .............................. [RUN]
[2025-10-25T12:11:04.571+0000] {subprocess.py:93} INFO - [0m12:11:04  10 of 10 ERROR creating sql table model core_core.shipping ..................... [[31mERROR[0m in 0.10s]
[2025-10-25T12:11:04.625+0000] {subprocess.py:93} INFO - [0m12:11:04
[2025-10-25T12:11:04.628+0000] {subprocess.py:93} INFO - [0m12:11:04  Finished running 10 table models in 0 hours 0 minutes and 5.73 seconds (5.73s).
[2025-10-25T12:11:04.793+0000] {subprocess.py:93} INFO - [0m12:11:04
[2025-10-25T12:11:04.796+0000] {subprocess.py:93} INFO - [0m12:11:04  [31mCompleted with 2 errors, 0 partial successes, and 0 warnings:[0m
[2025-10-25T12:11:04.799+0000] {subprocess.py:93} INFO - [0m12:11:04
[2025-10-25T12:11:04.801+0000] {subprocess.py:93} INFO - [0m12:11:04    Database Error in model orders (models/core/orders.sql)
[2025-10-25T12:11:04.802+0000] {subprocess.py:93} INFO -   syntax error at or near ""Order Status""
[2025-10-25T12:11:04.803+0000] {subprocess.py:93} INFO -   LINE 23:         "Order Status" as order_status,
[2025-10-25T12:11:04.803+0000] {subprocess.py:93} INFO -                    ^
[2025-10-25T12:11:04.804+0000] {subprocess.py:93} INFO -   compiled code at target/run/supply_chain_core/models/core/orders.sql
[2025-10-25T12:11:04.804+0000] {subprocess.py:93} INFO - [0m12:11:04
[2025-10-25T12:11:04.806+0000] {subprocess.py:93} INFO - [0m12:11:04    Database Error in model shipping (models/core/shipping.sql)
[2025-10-25T12:11:04.807+0000] {subprocess.py:93} INFO -   syntax error at or near ""Days for shipment (scheduled)""
[2025-10-25T12:11:04.808+0000] {subprocess.py:93} INFO -   LINE 23:         "Days for shipment (scheduled)" as days_for_shipment...
[2025-10-25T12:11:04.808+0000] {subprocess.py:93} INFO -                    ^
[2025-10-25T12:11:04.809+0000] {subprocess.py:93} INFO -   compiled code at target/run/supply_chain_core/models/core/shipping.sql
[2025-10-25T12:11:04.809+0000] {subprocess.py:93} INFO - [0m12:11:04
[2025-10-25T12:11:04.812+0000] {subprocess.py:93} INFO - [0m12:11:04  Done. PASS=8 WARN=0 ERROR=2 SKIP=0 TOTAL=10
[2025-10-25T12:11:07.296+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-25T12:11:07.297+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-25T12:11:07.314+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-25T12:11:07.320+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dataco_supply_chain_pipeline, task_id=dbt_run_core, run_id=manual__2025-10-25T12:09:49.010461+00:00, execution_date=20251025T120949, start_date=20251025T121048, end_date=20251025T121107
[2025-10-25T12:11:07.346+0000] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.10/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-10-25T12:11:07.347+0000] {email.py:271} INFO - Email alerting: attempt 1
[2025-10-25T12:11:11.391+0000] {email.py:282} INFO - Sent an alert email to ['bi@example.com']
[2025-10-25T12:11:13.085+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task dbt_run_core (Bash command failed. The command returned a non-zero exit code 1.; 2352)
[2025-10-25T12:11:13.121+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-25T12:11:13.154+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-25T12:11:13.160+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
